# Generated by Django 3.0.3 on 2020-03-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200302_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
