# Generated by Django 3.0.3 on 2020-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_entry_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gravatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
