# Generated by Django 3.0.3 on 2020-03-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_gravatar_url'),
    ]

    operations = [
        migrations.RenameModel('Entry', 'EntryEnvelope')
    ]
