# Generated by Django 3.0.3 on 2020-03-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200309_1619'),
    ]

    operations = [
        migrations.RenameField('Comment', 'entry', 'entry_envelope'),
        migrations.RenameField('EntryEnvelope', 'contents', 'entry'),
    ]
