# Generated by Django 3.0.3 on 2020-06-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200309_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryenvelope',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
