# Generated by Django 3.0.3 on 2020-06-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200604_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryenvelope',
            name='version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
