# Generated by Django 3.0.3 on 2020-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200609_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryenvelope',
            name='defunct',
            field=models.BooleanField(default=False),
        ),
    ]
