# Generated by Django 3.0.3 on 2020-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, default='https://www.thecodeblogs.com', max_length=255, null=True),
        ),
    ]
