# Generated by Django 3.1.2 on 2021-01-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_view_session_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='entry_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
