# Generated by Django 3.1.2 on 2021-01-22 17:25

from django.db import migrations

def convert_posted_links(apps, schema_editor):
    View = apps.get_model('blog', 'View')
    views = View.objects.all()
    for view in views:
        view.entry_id = view.entry_envelope.entry.get('id')
        view.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_view_entry_id'),
    ]

    operations = [
        migrations.RunPython(convert_posted_links, reverse_code=migrations.RunPython.noop),
    ]
