# Generated by Django 3.1.2 on 2021-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210124_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorprofile',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
