# Generated by Django 3.1.2 on 2021-01-26 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_visitorprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='interaction',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='view',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='view',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='visitorprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='visitorprofile',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
