# Generated by Django 3.1.2 on 2021-01-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210126_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='session_uid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
